/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching'

// Precache all assets generated by Vite
// @ts-ignore
precacheAndRoute(self.__WB_MANIFEST)

// Add Cross-Origin isolation headers to all fetch responses
// This replaces the functionality of coi-serviceworker.js
self.addEventListener('fetch', (event: any) => {
  const fetchEvent = event as FetchEvent
  fetchEvent.respondWith(
    fetch(fetchEvent.request).then((response) => {
      if (!response || response.status === 0) return response

      const newHeaders = new Headers(response.headers)
      newHeaders.set('Cross-Origin-Embedder-Policy', 'require-corp')
      newHeaders.set('Cross-Origin-Opener-Policy', 'same-origin')
      newHeaders.set('Cross-Origin-Resource-Policy', 'cross-origin')

      return new Response(response.body, {
        status: response.status,
        statusText: response.statusText,
        headers: newHeaders
      })
    })
  )
})

// Proper service worker activation
self.addEventListener('install', () => {
  // @ts-ignore
  self.skipWaiting()
})

self.addEventListener('activate', (event) => {
  // @ts-ignore
  event.waitUntil(self.clients.claim())
})
